### ISSUE TITLE
memory为空 从零开始 报 this.room.transport.draw is not a function

### ISSUE THREAD

**Issue by 923132714** [HoPGoldy/my-screeps-ai#21]
memory 空时会先找不到stats.rooms 添加后，报下面的错

```
TypeError: this.room.transport.draw is not a function
    at ControllerExtension.onWork  (../src/mount/StructureExtension/ControllerExtension/ControllerExtension.ts:15:24)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
    at Object.loop  (../src/main.ts:44:6)
[下午9:18:22][shardSeason]TypeError: this.room.transport.draw is not a function
    at ControllerExtension.onWork  (../src/mount/StructureExtension/ControllerExtension/ControllerExtension.ts:15:24)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
    at Object.loop  (../src/main.ts:44:6)
```
![image](https://user-images.githubusercontent.com/25949545/116700919-e80c4080-a9f9-11eb-8666-2c3b20f6db1b.png)

**Comment by 923132714** [comment]
更新了代码，好像解决了？
