### ISSUE TITLE
TypeError: this.room.work.draw is not a function

### ISSUE THREAD

**Issue by 923132714** [HoPGoldy/my-screeps-ai#36]
TypeError: this.room.work.draw is not a function
    at ControllerExtension.onWork  (../src/mount/StructureExtension/ControllerExtension/ControllerExtension.ts:14:19)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
    at Object.loop  (../src/main.ts:44:6)

**Comment by 923132714** [comment]
_.forEach(Game.rooms,(room,roomName)=>
{
    if(room.controller){
        delete room.memory.spawnList;
        room.memory.powerTasks ="";
        if(room.memory.factory)room.memory.factory.taskList=[];
    }
}
)
